module.exports = {
  appName: "Storybook App 1",
  batchName: "Storybook 1",
  branchName: "SB 1",
  parentBranchName: "parent 1",
  exitcode: true,
  testConcurrency: 50,
  xmlFilePath: "/Users/christopheremerson/Projects/storybook-react-applitools",
  jsonFilePath: "/Users/christopheremerson/Projects/storybook-react-applitools",
  tapFilePath: "/Users/christopheremerson/Projects/storybook-react-applitools",
  browser: [
    { width: 1024, height: 768, name: "firefox" },
    { width: 800, height: 600, name: "firefox" },
    { width: 100, height: 100, name: "firefox" },
    { width: 400, height: 400, name: "firefox" },
    { width: 100, height: 100, name: "firefox" },
    { width: 400, height: 400, name: "firefox" },
    { width: 1024, height: 768, name: "firefox" },
    { width: 800, height: 600, name: "firefox" },
    { width: 100, height: 100, name: "firefox" },
    { width: 400, height: 400, name: "firefox" },
    { width: 100, height: 100, name: "firefox" },
    { width: 400, height: 400, name: "firefox" },
    { width: 1024, height: 768, name: "chrome" },
    { width: 800, height: 600, name: "chrome" },
    { width: 100, height: 100, name: "chrome" },
    { width: 1024, height: 768, name: "chrome" },
    { width: 800, height: 600, name: "chrome" },
    { width: 100, height: 100, name: "chrome" },
    { width: 1024, height: 768, name: "chrome" },
    { width: 800, height: 600, name: "chrome" },
    { width: 100, height: 100, name: "chrome" },
    { width: 1024, height: 768, name: "chrome" },
    { width: 800, height: 600, name: "chrome" },
    { width: 100, height: 100, name: "chrome" },
    { width: 1024, height: 768, name: "chrome" },
    { width: 800, height: 600, name: "chrome" },
    { width: 100, height: 100, name: "chrome" },
  ]
};